services:
  - type: web
    name: planner-backend
    env: node
    region: ohio
    buildCommand: cd backend && yarn install && yarn run build
    startCommand: cd backend && yarn start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3333
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: CORS_ORIGIN
        value: https://plann-er.vercel.app
      - key: FRONTEND_URL
        value: https://plann-er.vercel.app
